version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 API-Blog.wsgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=API-Blog.settings.production
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=blog_db
      - POSTGRES_USER=yasmina
      - POSTGRES_PASSWORD=yasmina203
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
