version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: yasmina
      POSTGRES_PASSWORD: yasmina203
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data

  web:
    image: Yasmina203/blog_project:latest
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data_staging:
